services:
  # RDMA requires root, cannot specify a user
  vllm:
    image: vllm-node-tf5
    container_name: spark-vllm-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    mem_limit: 110g
    memswap_limit: 120g
    pids_limit: 4096
    network_mode: host
    shm_size: 64g
    devices:
      - /dev/infiniband:/dev/infiniband
    volumes:
      # configure, or omit this, per your needs
      # use a directory like this if you have models already downloaded to a specific location
      #- ${MODELS_BASEDIR}:/models
      # use this bind mount if you use hf to download and cache models for you
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      # unused on workers
      #- ${RAY_SCRIPT_DIR}/ray-start-head.sh:/opt/nvidia/entrypoint.d/99-ray-start-head.sh
      # persist generated caches, can also use to persist hf downloaded models, add an entry as necessary
      - ${HOME}/spark-vllm-docker/mods/fix-gemma4-tool-parser/run.sh:/opt/nvidia/entrypoint.d/99-ray-start-head.sh
      - cache-data:/root/.cache/vllm
      - cache-data:/root/.triton
      - cache-data:/root/.cache/flashinfer
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    environment:
      # - RAY_NODE_IP_ADDRESS=${NODE_IP_ADDRESS}
      # - RAY_OVERRIDE_NODE_IP_ADDRESS=${NODE_IP_ADDRESS}
      # - RAY_memory_monitor_refresh_ms=0
      # - RAY_num_prestart_python_workers=0
      # - RAY_object_store_memory=8589934592
      # - RAY_object_store_memory=1073741824
      - VLLM_HOST_IP=${NODE_IP_ADDRESS}
      - VLLM_MARLIN_USE_ATOMIC_ADD=1
      - MN_IF_NAME=enp1s0f1np1
      - UCX_NET_DEVICES=enp1s0f1np1
      - NCCL_IB_DISABLE=0
      - NCCL_SOCKET_IFNAME=enp1s0f1np1
      - NCCL_IB_HCA=rocep1s0f1,roceP2p1s0f1
      - GLOO_SOCKET_IFNAME=enp1s0f1np1
      - OMPI_MCA_btl_tcp_if_include=enp1s0f1np1
      - TP_SOCKET_IFNAME=enp1s0f1np1
      - NCCL_IGNORE_CPU_AFFINITY=1
      # 4GB disk cache for compiled CUDA kernels
      - CUDA_CACHE_MAXSIZE=4294967296
      - CUDA_VISIBLE_DEVIDES=0
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      # - NCCL_DEBUG=INFO
      #  --pipeline-parallel-size 1
    restart: unless-stopped
    command: >
      vllm serve google/gemma-4-26B-A4B-it
        --served-model-name main
        --max-model-len 262144
        --max_num_batched_tokens 8192
        --gpu-memory-utilization 0.20
        --port 8000
        --host 0.0.0.0
        --load-format fastsafetensors
        --enable-prefix-caching
        --enable-auto-tool-choice
        --tool-call-parser gemma4
        --reasoning-parser gemma4
        --quantization fp8
        --kv-cache-dtype fp8
        --tensor-parallel-size 2
        --nnodes 2
        --node-rank 1
        --master-addr 192.168.0.31
        --master-port 29500
        --headless

volumes:
  cache-data:
